// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package quotes

import (
	"database/sql"
	"time"
)

type Quote struct {
	ID       int32
	State    int32
	Quote    string
	Type     int32
	Inserter sql.NullString
	Inserted time.Time
}

type Type struct {
	ID   int32
	Name string
}
