// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package quotes

import (
	"context"
	"database/sql"
	"time"
)

const activateOldestQuote = `-- name: ActivateOldestQuote :exec
UPDATE quotes
SET state = 1
WHERE id = (
    SELECT id
    FROM quotes
    WHERE state = 0
    ORDER BY inserted ASC
    LIMIT 1
)
AND type = (
    SELECT id
    FROM type
    WHERE name = ?
)
`

func (q *Queries) ActivateOldestQuote(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, activateOldestQuote, name)
	return err
}

const getLatestQuoteByType = `-- name: GetLatestQuoteByType :one
SELECT q.id, q.quote, t.name AS type, q.inserter, q.inserted
FROM quotes q
JOIN type t ON q.type = t.id
WHERE q.state = 1 AND t.name = ?
ORDER BY q.inserted DESC
LIMIT 1
`

type GetLatestQuoteByTypeRow struct {
	ID       int32
	Quote    string
	Type     string
	Inserter sql.NullString
	Inserted time.Time
}

func (q *Queries) GetLatestQuoteByType(ctx context.Context, name string) (GetLatestQuoteByTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestQuoteByType, name)
	var i GetLatestQuoteByTypeRow
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Type,
		&i.Inserter,
		&i.Inserted,
	)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT q.id, q.quote, t.name AS type, q.inserter, q.inserted
FROM quotes q
JOIN type t ON q.type = t.id
WHERE q.state = 1
ORDER BY RAND()
LIMIT 1
`

type GetQuoteRow struct {
	ID       int32
	Quote    string
	Type     string
	Inserter sql.NullString
	Inserted time.Time
}

func (q *Queries) GetQuote(ctx context.Context) (GetQuoteRow, error) {
	row := q.db.QueryRowContext(ctx, getQuote)
	var i GetQuoteRow
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Type,
		&i.Inserter,
		&i.Inserted,
	)
	return i, err
}

const getRandomQuoteByType = `-- name: GetRandomQuoteByType :one
SELECT q.id, q.quote, t.name AS type, q.inserter, q.inserted
FROM quotes q
JOIN type t ON q.type = t.id
WHERE q.state = 1 AND t.name = ?
ORDER BY RAND()
LIMIT 1
`

type GetRandomQuoteByTypeRow struct {
	ID       int32
	Quote    string
	Type     string
	Inserter sql.NullString
	Inserted time.Time
}

func (q *Queries) GetRandomQuoteByType(ctx context.Context, name string) (GetRandomQuoteByTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getRandomQuoteByType, name)
	var i GetRandomQuoteByTypeRow
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Type,
		&i.Inserter,
		&i.Inserted,
	)
	return i, err
}

const typeExists = `-- name: TypeExists :one
SELECT COUNT(*) > 0 AS ` + "`" + `exists` + "`" + `
FROM type
WHERE name = ?
`

func (q *Queries) TypeExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, typeExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
